### ISSUE TITLE
Mismatch between this library and OSB schema

### ISSUE THREAD

**Issue by pmorie** [pmorie/go-open-service-broker-client#101]
As @luksa pointed out in #96, parts of this library's types don't match the OSB schema.

- The `ParameterSchemas` field of `Plan` should be called `Schemas` 
- The type `ParameterSchemas` should be called `Schemas`
- The `ServiceInstances` field of `Schemas` should be called `ServiceInstance`
- The `ServiceBindings` field of `Schemas` should be called `ServiceBindings`

**Comment by luksa** [comment]
Preliminary work here: https://github.com/luksa/go-open-service-broker-client/commit/9d92a62a118116cd946f6be5881ee12002fc8a41

Note that the names in the OpenAPI spec are slightly different (and more accurate IMHO). For example, there's [`ServiceInstanceSchemaObject`](https://github.com/openservicebrokerapi/servicebroker/blob/master/openapi.yaml#L489). I'd remove the "Object" suffix, but I like including "Schema" at the end. `ServiceInstanceSchema` is much clearer than `ServiceInstance`. 

Also note that this should really be called `ServiceInstanceSchemas` (plural), to make it consistent with `Schemas` and the fact that it actually contains multiple schemas (`create` and `update`, with each of them again containing multiple schemas: `parameters` and `response`). The naming should also be fixed in the spec itself. I've filed an issue [here](https://github.com/openservicebrokerapi/servicebroker/issues/450).

**Comment by pmorie** [comment]
@luksa I think now that https://github.com/openservicebrokerapi/servicebroker/pull/459 is closed, we can proceed with this, correct?
